### ISSUE TITLE
展出的文档地址不工作

### ISSUE THREAD

**Issue by ycMia** [ForteScarlet/CatCode#1]
开始对猫猫码产生兴趣之后 --- 我发现 [README.md](https://github.com/ForteScarlet/CatCode/blob/master/README.md) 中的 [文档地址](https://www.yuque.com/simpler-robot/catcode) 中并没有任何内容....
顺便, 因为Readme中没写太清楚, CatCode的应用场景有何? 可否达到防止注入攻击, 等 的效果?
>(Star了, 表示好奇w)

**Comment by ForteScarlet** [comment]
因为文档暂时没有时间写... 
因为猫猫码是需要进行转义的，（就像urlencode一样？），所以需要有所约定
猫猫码现在主要用于我的另一个机器人框架，用于表示一些特殊的消息，例如图片消息、AT(`@xxx`)消息等。
但是我觉得如果仔细想想，可能真的会有一定的注入风险...

**Comment by ForteScarlet** [comment]
顺便，感谢star~🙇‍

**Comment by ForteScarlet** [comment]
其实我稍微想了想，我感觉猫猫码本质上就是一种特殊的字符串而已，安全相关的问题我认为是需要解析者自行控制的。
> 我好像有点啰嗦了

**Comment by ycMia** [comment]
>其实我稍微想了想，我感觉猫猫码本质上就是一种特殊的字符串而已，安全相关的问题我认为是需要解析者自行控制的。

感谢告知w
确实, 我也觉得她很可爱
很期待项目未来进程哟w--(部分是因为我也在考虑未来在TG上的机器人的开发)

**Comment by ForteScarlet** [comment]
哈哈，而且我刚刚也稍微补了一些文档。

提到TG，我未来也有让我的[simple-robot](https://github.com/ForteScarlet/simpler-robot)框架支持TG-bot的打算，有兴趣可以考虑来先做个QQ机器人（唐突安利
